### ISSUE TITLE
question: dataset/place schema

### ISSUE THREAD

**Issue by reterraform** [mapseed/platform#1540]
apologies if this not appropriate to this list, but I am evaluating the latest mapseed platform/api and can't get my dataset places (the dataset specified in the flavor config) to load in my platform map, though they do show as successfully responding to the dataset request sent to the API, with a geojson response that 'appears' correct. I can get the same dataset places to load successfully as a map layer though. Can you suggest where to check in the code &/or configs to see what my places geojson might be missing, preventing the dataset loading to the map?

Thanks in advance for any tips re this!

**Comment by goldpbear** [comment]
Hello! Thanks for your interest in Mapseed. Apologies for the configuration trouble-- Mapseed is undergoing a lot of changes to the config schema and supporting microservices, and the documentation has fallen behind.

We have pretty limited capacity these days and we're focusing mostly on Mapseed customers, but I'd suggest looking at some of the other config files (in the `src/flavors` directory) to get an idea of the current schema. We try to keep the `defaultflavor` up to date with new schema changes. Let me know if that helps with questions.

Out of curiosity, what's your Mapseed use case? Are you trying to set up a flavor for personal use?

**Comment by reterraform** [comment]
Thanks for that info!  At this point, mostly just learning current open-source online mapping skills, so 'cutting my teeth' by setting up test dev instances of various packages etc; no definite 'use case' for any at this stage; more of a 'brainstorming' phase..

**Comment by goldpbear** [comment]
Ah, very cool. Yeah, there are a lot of good open source web mapping technologies these days.

If you're just getting into it, you might get more mileage from exploring Mapbox GL-JS directly. You can check out their [style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/) and some [examples](https://docs.mapbox.com/mapbox-gl-js/examples/) (if you haven't found them already).

The mapping part of Mapseed is basically just a set of abstractions around Mapbox (which are undergoing changes), so experimenting with Mapbox directly might be a better way to get up to speed.

You can also explore other tools in the Mapbox ecosystem. Two of the tools we've found useful are [tippecanoe](https://github.com/mapbox/tippecanoe) (for creating vector tiles that Mapbox can consume, and (turfjs)[https://turfjs.org/] (for doing geospatial analysis on geojson). But there's tons more.

Good luck!
