### ISSUE TITLE
Improve clustering

### ISSUE THREAD

**Issue by modulitos** [mapseed/platform#161]
Our clusters are pretty sparse. We should edit them to be more coherent, whether it be an image with a number or a pie chart representing the cluster's content. 

This is related to the "Coherent Clustering" section of issue #94

**Comment by futuresoup** [comment]
Current branch of this from @goldpbear is available for checkout at [goldpbear/iconClusterDesign](https://github.com/smartercleanup/platform/tree/goldpbear/iconClusterDesign)

**Comment by futuresoup** [comment]
Assigning @Jemalias - this is a great opportunity for him to learn how the config works when it comes to condition based styling.
