### ISSUE TITLE
"View on map" feature from list view has improper zoom level

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#165]
See http://map.12000raingardens.org/list or http://trees.heyduwamish.org/list

When you are in list view, click "view on map" and it should bring you into full zoom to the place record but does not.

**Comment by LukeSwart** [comment]
It looks like the previous zoom level is saved and used when reverting back to the map after clicking an item from the list. I agree, we should change this to move to the max zoom level when clicking on an item from the list view.

**Comment by futuresoup** [comment]
Good to know (for live demos). This would also be less of a problem if we had a better icon change that stands out better when place record is selected
