### ISSUE TITLE
Implement browserify for dependency management

### ISSUE THREAD

**Issue by LukeSwart** [mapseed/platform#173]
Let's load our Javascript dependencies as modules using the CommonJS module implementation Browserify.

This would be very useful for our static file collection and would help clean up some of the views. We should push it upstream to Shareabouts as well.

**Comment by teamomivida** [comment]
**Good reference:** 
[Browserify Handbook](https://github.com/substack/browserify-handbook)

**Comment by LukeSwart** [comment]
I might want to use this module for Browserify integration with Django: https://github.com/j0hnsmith/django-pipeline-browserify

And here is a nice guide as well: http://gregblogs.com/how-django-reactjs-and-browserify/

**Comment by LukeSwart** [comment]
This was resolved in #604
