### ISSUE TITLE
allow anonymous user to support(like) a place via support-button

### ISSUE THREAD

**Issue by reterraform** [mapseed/platform#2012]
Probably missing something obvious (again), but doesn't appear to be set in platform via anonymous_permissions in datasets section of config.json, nor do I see where it can be set in the API admin. Any tips/pointers much appreciated!

Thanks & CHEERS

**Comment by goldpbear** [comment]
Hello-- thanks for the inquiry! We were in the process of moving more of the permissions management to the backend of the system before we had to spin this project down, so the abilities of the `anonymous_permissions` section of the config file are limited.

If I remember right I think you can achieve what you want with the "dataset permissions" section in the Django backend (found on the admin page for a given dataset). I would try making a dataset permission with a value of `*` for "submission set" for the dataset(s) in question, then granting retrieve, create, update, and delete permissions.

**Comment by reterraform** [comment]
thanks for that info! I did update the DS accordingly in the API but, attempting to add a support anonymously from the map, I still get a challenge/response popup asking for credentials; seems like perhaps there's default anonymous 'creds' needed to be sent with the request that's missing in mine(?). I did notice that adding anonymous support works on the 2 mapseed community sites that I tested, so I'm wondering if that's due to their setttings, or are they perhaps an older version, pre-permissions changes you referenced(?).

**Comment by goldpbear** [comment]
Ah, right-- I believe that box pops up when other auth modes are not granting access. I'm not sure why the dataset permission is not working though...

You might also try an Origin permission: under the dataset in the admin panel, add an Origin (for example `localhost:8000` -- this would what you enter in the "Pattern" box). Once the Origin is created/saved, you can add permissions to it by clicking `Edit permissions` at the bottom of the Origin section. Then you can grant desired permissions on the `*` submission set (i.e. on everything).

**Comment by reterraform** [comment]
that worked like a charm!! many thanks for the tip!

CHEERS
