### ISSUE TITLE
Activate and test email notifications

### ISSUE THREAD

**Issue by mapseed** [mapseed/platform#26]
instructions here - https://github.com/openplans/shareabouts/blob/master/doc/CONFIG.md#email-notifications

**Comment by futuresoup** [comment]
Or we can use a django package: https://www.djangopackages.com/grids/g/notification/

**Comment by LukeSwart** [comment]
Note that we currently have a bug related to the multi-dataset feature where we are unable to produce the newly created place url into the notification email. You can see how `places` is currently hardcoed into the url here: https://github.com/smartercleanup/platform/blob/develop/src/sa_web/templates/new_place_email_body.txt so we'll need to pass the dataset slug into the new_place_email_body template context. 

To fix this, we'll need to re-implement our Django's `view.send_place_created_notifications` method to accept a dataset slug here: https://github.com/smartercleanup/platform/blob/develop/src/sa_web/views.py#L135 and pass the slug either in the request or as a separate parameter. That function gets called in our `views.api` method here: https://github.com/smartercleanup/platform/blob/develop/src/sa_web/views.py#L397 which we've already implemented to properly handle our multiple datasets.

**Comment by LukeSwart** [comment]
👍
