### ISSUE TITLE
Hand grab cursor not working on Duwamish

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#273]
Strangely, on the default flavors the "hand grab" icon to drag the map shows fine, but not on Hey Duwamish.

This is important because it lets users know they should drag the map to place their pins and navigate the site

**Comment by LukeSwart** [comment]
I confirmed that this is related to CartoDB's leaflet wrapper library. The "hand grab" icon goes away as soon as a CartoDB layer is loaded.

**Comment by futuresoup** [comment]
I think @justBanks made  a fix for this (?)

**Comment by LukeSwart** [comment]
I thought this was due to Carto, and that may be true, but the pboakland flavor has a hand grab icon as well as Carto layers, and the hand grab cursor doesn't disappear. This could be an interesting investigation for a new collaborator!
