### ISSUE TITLE
Add toxic release inventory data to map, apply meaning to dataset

### ISSUE THREAD

**Issue by modulitos** [mapseed/platform#308]
It would be great to add this dataset to Hey Duwamish (and Hey Willamette):

https://iaspub.epa.gov/triexplorer/quantity_fac?p_view=COFA&trilib=TRIQ2&sort=_VIEW_&sort_fmt=1&state=53&county=53033&chemical=All+chemicals&industry=ALL&year=2013&tab_rpt=3&fld=TRIID&fld=NUMFR&fld=NUMFA&fld=pprecon&fld=pprecof&fld=ppengon&fld=ppengof&fld=pptrton&fld=pptrtof&fld=pprela&fld=pprelb&fld=pprelc&fld=ppreld&fld=pprem

But the first step is to get it into a format that is usable, like a CSV. I believe the "download" button is broken, so we may have to resort to scraping the web page. Perhaps someone can write a script to help us out?

Here is a nice Python web scraping tool:
http://scrapy.org/
And this might work for those with a non-technical background:
http://scrapinghub.com/portia/

**Comment by jotok** [comment]
I took a shot at this but I haven't checked it very closely, let me know if it looks like there are errors or if there is additional information on the page that you'd like me to pull.

https://docs.google.com/spreadsheets/d/1UqxvdAnGhsRyfo4fKLWSDCiUgweI2gnfCt_H-GEpZew/edit?usp=sharing

**Comment by futuresoup** [comment]
Thanks @jotok! Now we need to figure out how to display this data in a meaningful way. General we import upload data to CartoDB, style it there, and then serve it into the community map at HeyDuwamish.org as a map layer.

May I ask about your interest in the project? I'm curious how you found us

**Comment by jotok** [comment]
Hi @futuresoup! I was at the Open Seattle meetup last week and I thought the project looked interesting.

I'm not familiar with CartoDB so I tried to install the API locally to see the database schema and get a better idea of how the data should be formatted to be pulled into the app. Unfortunately I hit a snag and I haven't been able to get it working yet. In the meantime, if you think the CSV should be formatted differently, it would be pretty easy for me to make adjustments. For example, I'm not sure if we need to keep the rows corresponding to the totals for each site, or if we should just recompute those as needed.

Right now the code is a small ruby script. I can post it somewhere if you think it would be useful.

**Comment by LukeSwart** [comment]
It looks like a model has been developed, called the [Risk-Screening Environmental Indicators (RSEI) Model](https://www.epa.gov/rsei), which has taken the TRI data above and normalized it into a risk score. The risk model seems like a good solution for our data display issues. Furthermore, there is a project called the [Toxic Trends Mapper](http://toxictrends.org/), which is already mapping this info!

It'd be nice to incorporate the Toxic Trends Mapper data as a layer onto Hey Duwamish. @lesserj is leading the development on that project, and gave a great talk about it at a [recent CUGOS meeting](http://cugos.org/meetings/2016/11/16/cugos_monthly/). Seems like we might be able to use his vector tiles on our map, which he generates from the data using [tippecanoe](https://github.com/mapbox/tippecanoe).
