### ISSUE TITLE
Fix cartodb legend so it displays when layer is checked

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#327]
We have a bug where the legend from a CartoDB layer will not display.

**Comment by futuresoup** [comment]
One thing to figure out with this issue: How do we handle the legend area when multiple layers are selected?


Also note: the legend display is poor on mobile, it takes up way too much real estate. 
A temporary fix would be to enable legend only on tablet size screens or larger, but this can be dealt with on another issue ticket.

**Comment by justBanks** [comment]
For starters, see commit [`6971e17`](https://github.com/justBanks/hey-duwamish/commit/6971e17d20d8ea1aa7feac36fe73808efe65035d) -- this works in the simplest case where this exactly one carto layer with a legend.

Trying to handle more than one legend seems fairly complicated. If you inspect the html element that is the carto layer, notice that the `cartodb-legend-stack` is absolutely positioned. Also, carto doesn't seem to provide any way to link a legend with its corresponding layer.

**Comment by justBanks** [comment]
**Commit [`67122ca`]**(https://github.com/justBanks/hey-duwamish/commit/67122caecb31ea75b8965f948fb9796711d2a1ca)

**Comment by justBanks** [comment]
Fixed by #427.

I feel like I've just completed a semester of jQuery and earned a certificate.

Would have also liked to make a recursive call of setLegendVisibility from inside itself, but for some reason couldn't get it to execute... So, a teeny bit of code duplication.
