### ISSUE TITLE
Update config docs

### ISSUE THREAD

**Issue by modulitos** [mapseed/platform#349]
We have updated the config significantly, especially with the new dyanmic forms and multidataset features, but we have not updated our docs. We should update the docs to help ourselves and other track how the config works. Here is the config doc: https://github.com/smartercleanup/platform/blob/master/doc/CONFIG.md

**Comment by goldpbear** [comment]
Note that some newer config documentation has been added to the wiki, although we should probably still update the docs files themselves.
