### ISSUE TITLE
Give users and admins ability to find and mark duplicates

### ISSUE THREAD

**Issue by mapseed** [mapseed/platform#37]

**Comment by geodesy99** [comment]
This is one small example that is the tip of an iceberg - once a community project has any complexity beyond a very narrow focus, it gets complicated. Basically, what's needed is an CMS ([Content Management System](http://en.wikipedia.org/wiki/Content_management_system)) of some type on some [framework](http://en.wikipedia.org/wiki/List_of_content_management_frameworks) that supports spatial content objects. For instance, [GeoNode]( http://geonode.org/ ) ( [examples](  http://geonode.org/gallery/)). Or [Plone](https://plone.org/) with [OpenLayers](http://openlayers.org/) spatial plugins. Most CMS have a basic 'approval' workflow ( like the moderator has in any forum). Open Atrium had the graphic below [graphic](http://openatrium.com/#!/#Features) which covers the basic feature set(s!) needed. The requested feature is a standard CMS function - you could implement this single feature, then the next, but eventually you have implemented an awkward semi-CMS. I would change this request to 'Select a CMS framework'. 
![openatriumfeaturesdl](https://cloud.githubusercontent.com/assets/742406/5796960/38c41d04-9f66-11e4-874d-e0fe186c0f7e.jpg)
