### ISSUE TITLE
Enable streetview level reporting

### ISSUE THREAD

**Issue by mapseed** [mapseed/platform#38]
You can see an example of this in the Vision Zero project

http://www.nyc.gov/html/visionzero/pages/dialogue/map.html#
https://github.com/openplans/shareabouts-sv-vision-zero

**Comment by geodesy99** [comment]
Two aspects (maybe more): 
The VZ project looks to be a fairly 'stock' deployment using the Google Streetview and Maps API ( and Streetview does allow upload for 'Custom' panoramas. This revolves around the classic FOSS vs Proprietary ( or mix) technology stack concerns. But Streetview is economically based on retail and road transportation, while on my look, it's the stuff not already or going to be in Streetview that matters. And what is the 'refresh rate'? 
But I wonder how much we could do with something like [OpenPano](http://openpano.org/) around the areas [we are concerned with]( http://openpano.org/demo/) ?
