### ISSUE TITLE
Make use of HTTP/2 on the server

### ISSUE THREAD

**Issue by Bilal-io** [mapseed/platform#392]
We ought take advantage of HTTP/2 especially since we need to load the website faster.
One important feature of HTTP/2 is making multiple requests at the same time (sending/receiving).

Here you can read more about HTTP/2: https://http2.github.io/
And since we're using Nginx we should check this: https://nginx.org/en/docs/http/ngx_http_v2_module.html 
or do more research.

While HTTP/2 does not require encryption and it can work with HTTP, most browsers made it clear that they won't support HTTP/2 unless it encrypted using HTTPS. So this should be considered.

**Comment by LukeSwart** [comment]
You can see our nginx config here (along with our other deployment configs): https://github.com/LukeSwart/docker-shareabouts/blob/master/frontend/nginx.conf

Since HTTP/2 requires SSL, we'll need to implement SSL first. However, we have a bug with SSL: #394 So we'll need to fix that first.
