### ISSUE TITLE
Control layer visibility when reporting

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#468]
When users create a new place, it's possible that the layer to which they're contributing will not visible, depending on how the story feature or legend controls have manipulated layer visibility. We should ensure that such layers are made visible when users submit a place.

**Comment by goldpbear** [comment]
Here's an example of layer visibility being controlled by the legend checkboxes:
https://github.com/smartercleanup/platform/blob/develop-0.7.0/src/sa_web/static/js/views/gis-legend-view.js#L37-L43

**Comment by futuresoup** [comment]
If it's easier, we can settle for now on just making sure the user submitted places i.e. "reports" layer is toggled when submitting a report. But I suppose if we can choose which layers to toggle it could be better that way. I believe @justBanks has a prototype of this functionality
