### ISSUE TITLE
Map stories: Story overviews

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#502]
Users need a navigable overview of a story as they're exploring it. An overview would show users where in a story they currently are, what other places/landmarks make up the story, and would make it possible to jump arbitrarily around a story by clicking directly on a place.

A sidebar would work well for this purpose, such as the sidebar on www.crimereports.com:

![screen shot 2016-10-27 at 1 14 39 pm](https://cloud.githubusercontent.com/assets/9222338/19783631/82cf280a-9c47-11e6-8f4c-f656f80a2cd0.png)

Interaction design work is needed to pin down exactly how this feature will work.

**UPDATE:** A few additional desired features:

- It would be nice for the sidebar to serve multiple purposes, such as the container for the activity stream if desired, as well as the container for story overviews. Tabs within the sidebar could facilitate this.
- The sidebar should be collapsible and expandable.

**Comment by goldpbear** [comment]
A few mockup ideas, based on a sidebar composed of tabs and tabs optionally composed of panes:

Story tab with story overview pane active:
![right-sidebar-mockup-01](https://cloud.githubusercontent.com/assets/9222338/21553742/f58ddb04-cdbe-11e6-99d6-dc263d3d6d42.png)

Story tab with individual story selected:
![right-sidebar-mockup-02](https://cloud.githubusercontent.com/assets/9222338/21553744/f8a47316-cdbe-11e6-9609-c03f403c8109.png)

Story tab with individual story selected and individual story item selected:
![right-sidebar-mockup-03](https://cloud.githubusercontent.com/assets/9222338/21553746/faf60d82-cdbe-11e6-889c-07f54c090f00.png)

Activity tab selected:
![right-sidebar-mockup-04](https://cloud.githubusercontent.com/assets/9222338/21553747/fd5ea7d2-cdbe-11e6-94ba-3d194ecb7ec6.png)

**Comment by futuresoup** [comment]
@darrencoen may want to weigh in at some point, as we will be doing dedicated stories for the Passenger Rail map

**Comment by goldpbear** [comment]
@darrencoen -- awesome, feel free to leave any thoughts!
