### ISSUE TITLE
Move away from JQuery (?)

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#533]
Just curious if we try to move away from JQuery.

See:
 * [jQuery considered harmful](http://lea.verou.me/2015/04/jquery-considered-harmful/)
 * [A Year Without jQuery](http://blog.wearecolony.com/a-year-without-jquery/)

**Comment by goldpbear** [comment]
We might be overusing jQuery a bit for basic DOM stuff, but jQuery is wired in pretty closely to the project. It's the interface between Backbone and the DOM, and we're using a couple of jQuery plugins for datepicker and colorpicker functionality.

In my opinion it's not worth removing it entirely at this point, but there might be places where we can replace jQuery calls with native calls instead.

**Comment by goldpbear** [comment]
Closing--this will be addressed in #729
