### ISSUE TITLE
Create tiled view of reports

### ISSUE THREAD

**Issue by mapseed** [mapseed/platform#56]
We can currently see reports either as items in the Activity Stream on the sidebar, or in the "See all reports" list view here: http://heyduwamish.org/list

The information can be better displayed as tiles. Two layout are options are to have the tiles be the same size or have them be a variable size based on the length and size of the report.

(see attachments)

![tiled-reports-samesize](https://cloud.githubusercontent.com/assets/7245803/7129552/df0a3d04-e216-11e4-9523-9d8faaad93ba.png)
![tiled-reports-varioussize](https://cloud.githubusercontent.com/assets/7245803/7129553/df0a8dea-e216-11e4-88fb-34c56326e9d0.png)

**Comment by futuresoup** [comment]
Here's a little CSS that could help get us started
http://codepen.io/hugo/pen/MwVRJq
