### ISSUE TITLE
Reinvestigate lazy loading map layers

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#602]
There are still noticeable differences in loading times between maps with few layers and maps with several layers, even if those layers are set to be invisible by default. Setting layers to be invisible by default *should* prevent them from loading until they are activated in the sidebar. It's worth revisiting the lazy loading feature to make sure it's working as expected.

**Comment by zmbc** [comment]
I'm fairly certain this has never worked on Shareabouts layers. Could that explain what you're seeing?

**Comment by goldpbear** [comment]
Yes, Shareabouts layers definitely don't lazy load. Closing this as I haven't been able to reproduce a situation where other layers don't lazily load.
