### ISSUE TITLE
Consolidate layer grouping

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#612]
> instead of making one Mapseed "layer" that includes many ESRI layers (but can't mix ESRI and non-ESRI), have one item in the legend correspond with multiple Mapseed layers.

> This would have the upside of immediately giving this functionality to all kinds of layers, as opposed to just ESRI

**Comment by goldpbear** [comment]
Is this issue covered by what's introduced in #659? That PR gives us the ability to arbitrarily group layers into composite layers controlled by a single checkbox in the layers panel.

Not sure if this is a different issue though...

**Comment by zmbc** [comment]
I think they're the same. Just to clarify: can that PR allow grouping of any kinds of layers (GeoJSON, ESRI, etc)?

**Comment by goldpbear** [comment]
Right, it should work for any combination of layers. #659 doesn't actually create any new layer groups, it just wires together existing layer groups under the control of a single sidebar checkbox.

**Comment by zmbc** [comment]
You say potato, I say potato :laughing: 
That's exactly what I had in mind for this issue. Closing.

**Comment by goldpbear** [comment]
Ah, ok. Hope I didn't step on anyone's toes here! I didn't realize at first that we had two issues open for this feature, and I was working off the other one (#557).

**Comment by zmbc** [comment]
But that issue is a subset of this one, which is why I asked my initial question: that one only concerns Shareabouts layers. I think you should just note in your PR that it closes that issue, *plus* allows grouping together any set of any types of layers.

**Comment by goldpbear** [comment]
Gotcha--will do.
