### ISSUE TITLE
Mark reports as resolved

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#614]
We need a way to mark reports as resolved.

For example this complaint has been fixed - http://heyduwamish.org/report/498 - I think it's a good idea to archive it gracefully, meaning, mark it in a way that symbolizes to the user that it's been fixed (transparent graphic with a checkbox through it?) but keep it there so people can know it was an issue and feel good that something has actually been resolved (improves community morale).

**Comment by goldpbear** [comment]
@futuresoup -- what do you think about this approach to resolved reports:

<img width="1275" alt="screen shot 2017-03-15 at 5 10 59 pm" src="https://cloud.githubusercontent.com/assets/9222338/23976085/7ff4a0f6-09a2-11e7-92d4-88bb452a444a.png">
