### ISSUE TITLE
Localize on client side

### ISSUE THREAD

**Issue by zmbc** [mapseed/platform#688]
_(Part of #655)_

Notes (for myself and others):
- [This is what we're currently using](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/)
- [These tags](https://github.com/mapseed/platform/blob/6dcd9139054380161702d7aaa808fbcb37ab8e04/src/base/templates/base.html#L293-L294) compile all our [Handlebars templates](https://github.com/mapseed/platform/tree/master/src/base/jstemplates) through the localization system before registering them as partials within the page

How I envision this working:
- Use [jquery.i18n](https://github.com/wikimedia/jquery.i18n) -- convert the current locale files into that "banana" format
- Register the localization function as a Handlebars helper, and replace the Django localization calls with it
- Store the locale in `localStorage` (to emulate what Django's doing, which is, I believe, using a session)
- On locale change, dynamically grab the new banana file and either send out some "rerender" signal to all templates or (easier) just refresh the page

**Potential issue:** We take advantage of our two-step templating process by "localizing" strings that _themselves contain Handlebars template syntax_ ([for example](https://github.com/mapseed/platform/blob/master/src/base/locale/es/LC_MESSAGES/django.po#L65-L140)). There's probably a hacky way to emulate this on the client-side, but it's really not a good way to localize and maybe we should just fix it as part of this change.

**Comment by zmbc** [comment]
@goldpbear I don't think this is done? Simply using the multiple `index.html` copies wasn't what I had in mind. I think we can de-prioritize this a bit, though, because we've found a workaround.

**Comment by goldpbear** [comment]
@zmbc -- ah right, sorry, I got in an issue-closing mood after merging the static site. Agreed there is more we can do to improve localization as detailed in this issue. Reopening.
