### ISSUE TITLE
Spiderfying and clustering for CPS flavor

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#714]
The CPS flavor will likely have numerous groups of points that are very close to one another. We should "spiderfy" these points (i.e. place a small amount of distance between nearby points) as they're added to the map to prevent usability issues stemming from overlapping icons.

We should also cluster points together at low zoom levels.

**Comment by LukeSwart** [comment]
Not sure if this helps, but I know the leaflet marker cluster plugin "spirals" a cluster of points when it is clicked on. I wonder if it has a config option to improve this feature, or "spiderify" the points instead.

Here's an example:
![out-1](https://cloud.githubusercontent.com/assets/4207017/26117357/1ecfc0b8-3a1b-11e7-958c-d1845e749b0d.gif)

**Comment by goldpbear** [comment]
Yeah, I was hoping that plugin would allow us to just tweak the threshold that triggers spiderfying. I *think* the spiral feature on raingardens is a form of spiderfying in action for points directly on top of one another.

**Comment by goldpbear** [comment]
Also, that's a ton of raingardens on top of each other.
