### ISSUE TITLE
Best practices: modifications to third-party libraries

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#781]
Does anyone know if there are conventions or best practices around using third-party libraries that we modify slightly for our own purposes? I've been moving libraries like this with their changes to the `src/base/static/libs` directory.

But this approach is potentially problematic. The specific changes to third-party libraries are not recorded anywhere, making it difficult to update those libraries down the road. 

Are there conventions for documenting changes to third-party libraries, such that we can easily re-incorporate those changes to newer versions down the road? @zmbc @LukeSwart -- do you guys have thoughts/experience with this issue?

**Comment by zmbc** [comment]
- We should comment where we have made changes; this will make it possible (though still difficult) to upgrade
- If the change is something generally useful, we should make a PR on the library itself. If we could get it merged, then we could go back to using the standard version.
- If the change is something pretty Mapseed-specific, we should consider whether there's a way to create a wrapper layer around the library that does what we need, instead of modifying the source itself.

**Comment by goldpbear** [comment]
@zmbc -- sounds very reasonable to me. I have a feeling that a lot of our changes will fall into the "Mapseed-specific" category, but I agree that opening a PR on the third party project would be the best option when available.

**Comment by goldpbear** [comment]
Ok, followup question: we have an npm module (the `accessible-autocomplete` module, for rendering autocomplete comboboxes), which required changes for it to be useful to us. I made the changes in the module source (I don't think there's a way to make a wrapper in this case, because the changes are to internal methods), rebuilt it, and put the built, minified version in our `js/libs` folder.

But what becomes of the modified source? How can we keep track of those changes, other than inserting comments in our minified `js/libs` folder?

**Comment by zmbc** [comment]
@goldpbear It would be best if the minification was done in the build process--in fact, doing a vendor bundle with webpack is something I keep forgetting to do.

**Comment by goldpbear** [comment]
I guess I'm still not clear on how best to track changes that we make to vendor source files. Comments we leave will be minified out in the build. Do we keep an external file of changes we make?

**Comment by LukeSwart** [comment]
In this kind of situation, where we are forking another module, I would suggest that we fork the original repo. Copy/pasting the original library and minifying it in our build, as discussed above, can also work. But if we want to track our changes and pull from upstream, I think we should fork the original module and republish under another name. That way we can track our changes on our forked, and pull from upstream as needed. Then we can publish that repo to npm and pull it into our project as a regular module.

And if publishing to npm is too much of a hassle, we can always have our package.json pull in modules directly off of github, like so:

```
"@mapseed/new-module": "https://github.com/mapseed/new-module-repo-name.git#14664d5b3dee563b0916913879f0ca5e56f5cc44",
```

and that goes under our `package.json`'s `dependencies` section, where that sha refers to a specific commit's sha in that repo. Then we can require that new module via `require('mapseed/new-module')`.

Does that help?

**Comment by goldpbear** [comment]
I like the idea of forking and pulling directly from github. I think I'll try to get our change incorporated into the base project before publishing a whole separate version on npm.
