### ISSUE TITLE
Error loading one or more datasets

### ISSUE THREAD

**Issue by alimon808** [mapseed/platform#817]
![screen shot 2017-09-30 at 3 29 50 pm](https://user-images.githubusercontent.com/858582/31050050-10ad9e1a-a5f5-11e7-8e6c-050fc06391b8.png)

**Comment by goldpbear** [comment]
This is probably caused by missing `.env` keys. We're going to be moving away from dependence on a `.env` file in the very near future, but in the meantime try adding these lines to your `src/.env` file:

```
DUWAMISH_SITE_URL=https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/duwamish
DUWAMISH_DATASET_KEY=MGMzOWU2ZmUwZmFkZDYzZTI1ZmQ3MDhi

VISION_SITE_URL=https://dev-api.heyduwamish.org/api/v2/thebestguest/datasets/vision
VISION_DATASET_KEY=YjdjNDk3ODkzN2IyZjQ0M2NiMWIxNzM5

RESTORATION_SITE_URL=https://dev-api.heyduwamish.org/api/v2/thebestguest/datasets/restoration
RESTORATION_DATASET_KEY=ZDg1ZmM5YmFhOTkzYTliNTM4MWJlMDI1

TREES_SITE_URL=https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/trees
TREES_DATASET_KEY=YmIxZjA1OTlmNjUxYWM5NDgwM2Q5NmMx

DUWAMISHFEATURED_SITE_URL=https://dev-api.heyduwamish.org/api/v2/thebestguest/datasets/duwamishfeatured
DUWAMISHFEATURED_DATASET_KEY=OTdhZjkyNWQ2M2U2NTE0YzIwNmM0Njhi

AIR_SITE_URL=https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/air
AIR_DATASET_KEY=NmYxZjhmNTUxZjhiZmViMThjZGU4ZDJh
```

**Comment by alimon808** [comment]
This error is on the production site.

**Comment by goldpbear** [comment]
Ah, thanks for the heads up! It looks like we're pointing to one dev-api dataset on the production site, and that dataset got clobbered when we synced the dev-api Thursday night. It should be back to normal now.
