### ISSUE TITLE
Conditional library loading?

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#825]
I'm wondering if it's possible to conditionally load third-party libraries (or even chunks of our own codebase) based on user behavior. For example, many users of a Mapseed site will have no use for the `leaflet-draw` library (because they'll never draw geometry on the map), but that library is still transferred to every client. There are many other examples of similar situations. I think there could be a nice performance boost if we conditionally load certain libraries only when needed by the user.

@LukeSwart @zmbc @alimon808 @sjb3 -- do you guys know if there are standard ways/best practices for handling this?

**Comment by zmbc** [comment]
@goldpbear I'd suggest using [Webpack's code splitting feature](https://webpack.js.org/guides/code-splitting/) for this. It adds a bit of complexity to using `require`s that are loaded separately, but has the end result that certain code is only requested if a specific code path is run. For a concrete example of how to do this, check out [this Webpack lazy loading guide](https://webpack.js.org/guides/lazy-loading/).
