### ISSUE TITLE
deploy script limitations

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#832]
I like the `deploy.js` script we're using to deploy static sites to S3, but I think it has one major limitation: you can't set metadata (and thus headers) with it, at least not without [some jankiness](https://github.com/mapseed/platform/blob/master/scripts/deploy.js#L25-L45).

I'm realizing now that we might actually want to set a lot of headers on our S3-hosted content. For example, we want to reliably set the `Content-Encoding: gzip` header for anything with a `.gz` file type, and ideally we'd have fine-grained control over the `Cache-Control` header for certain types and directories of files.

[This issue](https://github.com/klaemo/s3-website/issues/42) on the `s3-website` repo is not giving me a lot of confidence that the current maintainers will add header/metadata functionality to their script in the future.

So the question is, do we keep using this tool? Do we fork the project and add our own metadata handling?

@zmbc @LukeSwart -- thoughts?

**Comment by zmbc** [comment]
@goldpbear I think a fork may be in order, but as the total amount of code is still fairly low, I've just done it in the `deploy.js` script. (See #833--this is now not nearly as janky as the code you linked to). There is also one other custom thing, the CloudFront configuration, which could also be included in this proposed fork (or even better, a PR to the original project).
