### ISSUE TITLE
Stable URL model

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#879]
We have a feature that allows creators of featured sites to define a custom url for their post, such as:
```
heyduwamish.org/concord
```
These urls are checked for uniqueness on the client before submission, but there is no server-side guarantee of uniqueness either within or across datasets. Although this is manageable for now, a URL scheme like this is probably not sustainable on a SAAS platform.

Here's a proposal for an alternative URL scheme, which would apply to all content generated by users:
```
heyduwamish.org/12345/concord
```
where `12345` is the unique global identifier assigned by the database, and `concord` is either an auto-generated slug (derived from the title of the post, say), or a user-defined slug (for posts where we want to grant users the ability to set their own slugs).

We'd also have to support URL routing for legacy-style urls, which include URLs like `/concord` but also include URLs like `/trees/294`, which make use of a dataset slug (`trees` in this case) defined in the config. The slug isn't strictly necessary to guarantee uniqueness however. Supporting routing for these legacy urls would be easy on the client.

**Comment by goldpbear** [comment]
Ruh roh, I forgot that the slug in place urls (e.g. `trees` in `/trees/294`) is actually needed to make a direct lookup on the API. The slug tells the client which dataset to hit. 

So the `/12345/custom-url` scheme might not work so well. Maybe we can do this instead:
```
/dataset-slug/id/custom-slug
```
e.g.:
```
/trees/294/this-is-a-great-tree
```
