### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Brian393** [mapseed/platform#994]
Hello -

First, Mapseed is a brilliant application, and I am also glad to see the link to Que pasa Riachuelo? I met some of the people down there who worked on that.

I'm an artist and writer in Chicago who does GIS and works with eco-activism. I would like to propose a Mapseed flavor to an international group of artists and researchers doing a Mississippi river project, and then a little later to a couple of community projects in the Pacific Northwest.

Although I'm a seriously amateur programmer I managed to put together a working demo for the Mississippi project, using the Willamette flavor. It is on my repo at https://github.com/Brian393/platform  (master and AnthroDemo2 branches). Runs perfect on localhost:8000.

I have two questions:

1. When I run "FLAVOR=willamette npm run build" on the Linux terminal it says "(STATIC SITE BUILD) (SUCCESS) BUILD FINISHED for willamette". However when I click "index.html" in the www folder it just says "Loading Data…" on the browser window and nothing happens. Same result when I upload the www folder to my server. Are there more detailed instructions? Can someone help me get this demo online, so I can show it to the group?

2. If they like it - which I think they will - I would have a small budget for setup and modification of a production site. Would anyone like to help me with this? I would be paying out of pocket, but I would be happy to do it in order to set the project on a firm foundation. I also want to learn this stuff on my own, so just a little free help and advice would be an equally agreeable solution, it's up to you.

thanks for all the cool stuff you do,

Brian Holmes

**Comment by futuresoup** [comment]
Hi Brian - thanks for the kind words, and of course, we'll hook you up!

Jump on our Gitter channel and let's talk:
https://gitter.im/mapseed/Lobby

**Comment by Brian393** [comment]
OK, excellent, I am on it now.
